        openDraftPR: true
        gitSafeReplacementChar: '-'
        mode: chatops
        branchName: 'FnRx-issue-${issue.number}'
        autoCloseIssue: true
        branches:
            - label: seção
              name: master
