@startuml

!theme plain


(Reactive Programming) <-up-> (Reactive Manifesto)
(Reactive Programming) <-up-> (Sync vs Async)
(Reactive Programming) <-up-> (RxJava Reactive Streams)
(Reactive Programming) <-up-> (Callback Hell)
(Reactive Programming) <--> (RxJava The Big Picture)
(Reactive Programming) <--> (Concurrent vs Parallel Programming)
(Reactive Programming) <--> (Observer Design Pattern)
(Reactive Programming) <--> (Push vs Pull)

@enduml
